name: Build and Deploy Java Application

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.PROJECT_ID }}/App:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.PROJECT_ID }}/App:latest

      - name: Deploy
        run: |
          gcloud run deploy App \
          --region europe-west1 \
          --image gcr.io/${{ secrets.PROJECT_ID }}/App \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.PROJECT_ID }}
